# SimplePlugins - SimpleKills
# Placeholders
#    %attacker%     - Username of the player that killed the victim
#    %victim%    - Username of the player that is a noob

run-commands:
  - say %attacker% killed %victim%
  - say %victim% is a l0z3r
  - eco give %attacker% 1
